### ISSUE TITLE
I installed the offices but the script did not work Please answe

### ISSUE THREAD

**Issue by muhommadalmusawi** [Theodolus/SETClone#1]
I installed the offices but the script did not work
Please answer

python fsattacks.py
Traceback (most recent call last):
File "fsattacks.py", line 51, in
from src.core.setcore import *
ImportError: No module named src.core.setcore

**Comment by Theodolus** [comment]
You should be asking this on the actual SET git page: https://github.com/trustedsec/social-engineer-toolkit This was a clone I created for testing purposes and then forgot about.
